"""
Django settings for my_chat_project project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from pathlib import Path
import os

# プロジェクトのルートパス
BASE_DIR = Path(__file__).resolve().parent.parent

# シークレットキー（あなたの初期設定のキーをそのまま使用します）
SECRET_KEY = 'django-insecure-5$&4ac*&hrm!@iahppj+0k91kj$7)7e92ziutzmpdc$vfviz_n'

DEBUG = True

# ⭕ 他のパソコンやスマホからのアクセスをすべて許可します
ALLOWED_HOSTS = ['*']

# ⭕ Serveo経由でのログインやアカウント送信（CSRFセキュリティ）をすべて許可します
CSRF_TRUSTED_ORIGINS = ['https://*.serveousercontent.com', 'https://*.serveo.net']

# アプリケーション定義
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat', # アプリ登録
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_chat_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # ⭕ プロジェクト直下の templates フォルダを探しに行く設定に修正
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # ⭕ デバッグ用の設定を復旧
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_chat_project.wsgi.application'

# データベース設定
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# パスワードバリデーション（研修のテスト用として登録しやすいようにチェックを無効化しています）
AUTH_PASSWORD_VALIDATORS = []

# 国際化設定（⭕ 日本語・日本時間に設定を修正）
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True

# 静的ファイルの設定
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ログイン・ログアウトの自動ジャンプ設定
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chat_room'
LOGOUT_REDIRECT_URL = 'login'

# アップロードされたファイルを保存する物理フォルダの場所
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ブラウザからファイルにアクセスするためのURLの始まり
MEDIA_URL = '/media/'

