# Generated by Django 5.2.15 on 2026-06-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
